kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ocs-metrics-exporter
rules:
- apiGroups:
  - ceph.rook.io
  resources:
  - cephobjectstores
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - quota.openshift.io
  resources:
  - clusterresourcequotas
  verbs:
    - get
    - list
    - watch
